import Navbar from './components/header/navbar/NavBar'
import Footer from "./components/Footer/Footer";
import './globals.css'



export const metadata = {
  title: 'Dine Mart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>
            <Navbar />
        </div>
        <div>
        {children}
        </div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
